version: '3'

services:

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - PORT=3000
      - DATABASE_CONN=mongodb://database:27017/surreal-estate?authSource=admin


  database:
    image: mongo:4.4.14
    restart: unless-stopped